stages:
  - build

variables:
  NPM_CONFIG_CACHE: "$CI_PROJECT_DIR/.npm"

cache:
  paths:
    - .npm/
    - node_modules/

before_script:
  - node --version || (sudo apt-get update -qq && sudo apt-get install -y -qq curl && curl -fsSL https://deb.nodesource.com/setup_18.x | sudo bash - && sudo apt-get install -y nodejs)
  - npm ci --cache .npm --prefer-offline

build:
  stage: build
  tags:
    - shell
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  only:
    - merge_requests
    - main
